app:
  name: CurrencyExchangeApp
  port: 8081
  host: localhost
  secret: zajednički_ključ+gt4wdfhy9

database:
  host: localhost
  port: 3306
  user: root
  password: root
  name: currency_exchange
  MaxOpenConns: 10
  MaxIdleConns: 5
  ConnMaxLifetime: 10