app:
  name: CurrencyExchangeApp
  port: 9001
  host: localhost

database:
  host: localhost
  port: 3306
  user: root
  password: root
  name: currency_exchange
  MaxOpenConns: 10
  MaxIdleConns: 5
  ConnMaxLifetime: 10